### ISSUE TITLE
Support single json object in validation

### ISSUE THREAD

**Issue by philippeagra** [ekino/jcv-db#1]
Hello, it would be cool that queries returning a single result could be validated with a json object like that:
```kotlin
    dBComparatorBuilder
        .build("select * from person")
        .isValidAgainst("""
          {
            "id": "{#uuid#}",
            "name": "test",
          }
        """
```

**Comment by leomillon** [comment]
@philippeagra what's the problem with `[]` wrapping?
```kotlin
dBComparatorBuilder
        .build("select * from person")
        .isValidAgainst("""
          [{
            "id": "{#uuid#}",
            "name": "test",
          }]
        """
```

**Comment by philippeagra** [comment]
@leomillon There is no problem with it but a bit like spring-data differentiates the `findOne` and `findAll` for the same `select` request, unwrapping the expected row into a single json object makes sence for me.
I think that most of the time you will make assertions on a single row (adding a `where` clause) and the unwrapped array will improve readability.
