### ISSUE TITLE
Remove dependencies on org.json

### ISSUE THREAD

**Issue by clemstoquart** [ekino/jcv-db#16]
There are multiple occurrences of org.json.JSONObject on the class path :
<img width="320" alt="image" src="https://user-images.githubusercontent.com/1222144/78671194-404c3e00-78df-11ea-841d-b70edcc813a9.png">
and 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1222144/78671260-59ed8580-78df-11ea-85b1-60038dbdfd62.png">

It should be possible to remove the direct dependencies on org.json:json.

**Comment by MrAolen** [comment]
#17
